In [2]:
# Numpy Arrays Intro (1-d arrays, 2-d matrices)

In [4]:
#declaring & viewing list
my_list=[1,2,3]
my_list

[1, 2, 3]

In [10]:
# cast a list as an array
import numpy as np
arr=np.array(my_list)
arr

array([1, 2, 3])

In [12]:
# matrices are list of lists
my_mat=[[1,2,3],[4,5,6],[7,8,9]]
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
mat=np.array(my_mat)
mat
# [] brackets represent the dimension of arrays
# two [[ and ]] represents 2d array i.e matrices

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [59]:
# arange(start, stop, step, dtype=None)
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
# returns "integers" over specific interval=3
np.arange(0,10,3)

array([0, 3, 6, 9])

In [27]:
# creating arrays with 0
np.zeros(4)

array([0., 0., 0., 0.])

In [51]:
# passing touple to specify matrices dimension (columns,rows)
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# linspace = "evenly spaced numbers" over specific interval
# linspace(start, stop, number_of_points_required)

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [40]:
# Identity matrix eye(vectors)
# a square matrix in which all the elements of the principal diagonal are ones and all other elements are zeros.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [111]:
# generate arrays of random numbers (0-1)
'''
Alternate declaration
import numpy as np
from np.random import rand
rand(5)
'''
np.random.rand(5)


array([0.28454638, 0.42545919, 0.74613699, 0.61098455, 0.55176537])

In [45]:
# generate matrices of random numbers (0-1)
# no touple for random function, pass only integers
np.random.rand(3,3)

array([[0.3282276 , 0.500903  , 0.7629453 ],
       [0.85243643, 0.24858119, 0.72517074],
       [0.70004338, 0.60517917, 0.01837359]])

In [52]:
# 'randn' return samples fgrom normal or gaussian distribution
# data is centered around 0, range -1 to +1
np.random.randn(5,3)

array([[-1.30728042,  0.87878258, -0.30181006],
       [ 1.60442546,  1.43143788, -0.34180567],
       [-1.90230083,  0.51235053,  0.26116426],
       [-0.53249582, -0.97805787,  0.26180137],
       [-1.10278373,  1.58664861, -1.0312969 ]])

In [60]:
# randint returns random integers in ascending order
# randint(low, high, size=number of integers)
# low inclusive, high exclusive
np.random.randint(1,100,10)

array([20, 99, 62, 69, 32, 44, 98, 52, 98, 72])

In [68]:
arr=np.arange(30)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [65]:
ranarr=np.random.randint(0,100,15)
ranarr

array([62, 31, 24, 96, 57, 59, 30, 37, 20, 31, 75, 42, 62,  9, 57])

In [73]:
# number of elements in arr must be a multiple of reshape columns & rows
# convert an array into matrices
arr.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [89]:
resh=ranarr.reshape(5,3)
resh


array([[62, 31, 24],
       [96, 57, 59],
       [30, 37, 20],
       [31, 75, 42],
       [62,  9, 57]])

In [90]:
# max() and min() values in array
arr.max()

29

In [91]:
resh.min()

9

In [93]:
ranarr

array([62, 31, 24, 96, 57, 59, 30, 37, 20, 31, 75, 42, 62,  9, 57])

In [94]:
# argmax() and argmin() to check the index location of the values

In [95]:
ranarr.argmax()

3

In [96]:
ranarr.argmin()

13

In [102]:
# shape() for checking the shape of arrays/ matrices
arr.shape

(30,)

In [104]:
ranarr.shape

(15,)

In [107]:
# check dimensions of reshaped array
resh.shape

(5, 3)

In [108]:
# check data_type of variables
ranarr.dtype

dtype('int64')